name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # or the version you're using

      - name: Install dependencies
        run: npm install

      - name: Set Jest permissions
        run: chmod +x ./node_modules/.bin/jest # Adds executable permission

      - name: Build the project
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # or the version you're using

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx jest
